# Generated by Django 5.1.1 on 2024-10-30 10:09

import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurants.models.dish_upload_path),
        ),
    ]
