# Use a Node.js base image
FROM node:18

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all frontend files
COPY . .

COPY public /app/public 
# Build the project
RUN npm run build

# Expose the port used by the app
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
