apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: backend
    spec:
      containers:
      - image: himani3/ubereats-backend:latest
        name: backend
        ports:
        - containerPort: 8000
          protocol: TCP
        volumeMounts:
        - mountPath: /app/media
          name: backend-cm0
        - mountPath: /app/media
          name: media-volume
      restartPolicy: Always
      volumes:
      - configMap:
          name: backend-cm0
        name: backend-cm0
      - hostPath:
          path: C:\MSDA\sem 2\Data 236\lab\lab2-uber-eats\backend\media
        name: media-volume
