services:
  backend:
    image: himani3/ubereats-backend
    volumes:
      - ./backend/media:/app/media
    ports:
      - "8000:8000"

  frontend:
    image: himani3/ubereats-frontend
    volumes:
      - ./frontend/public:/app/public
    ports:
      - "3000:3000"
