services:
  backend:
    image: himani3/lab2-uber-eats-backend
    volumes:
      - ./backend/media:/app/media
    ports:
      - "8000:8000"

  frontend:
    image: himani3/uber-eats-frontend
    volumes:
      - ./frontend/public:/app/public
    ports:
      - "3000:3000"
docker pull himani3/uber-eats-frontend:latest
