version: "3.8"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/media:/app/media
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ../frontend/public/images:/app/images
    ports:
      - "3001:3000"

volumes:
  images:
