# Generated by Django 5.1.1 on 2024-10-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_profile_picture'),
        ('restaurants', '0004_alter_dish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='favorites',
        ),
        migrations.AddField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='restaurants.restaurant'),
        ),
    ]
