apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: himani3/ubereats-frontend:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /app/public/images
          name: images-volume
      volumes:
      - name: images-volume
        hostPath:
          path: /app/build/images
